/**
 * Automated Verification Script: Milestone 3 Task 3 - Real-Time Clinical Alert Engine & Escalation System
 * 
 * Verifies:
 * 1. Engine SLA Benchmark Statistics (Response Target <= 3.2m, Compliance >= 95%, MTTN)
 * 2. Active Alerts & Cohort Filtering API
 * 3. Sarah M. (P002) Signature AFib Spike Incident Simulation (145 bpm, |Z| > 2.5σ)
 * 4. Clinical Decision Support (CDS) Order Sets Generation (STAT ECG, Labs, Meds)
 * 5. Clinician Response SLA Acknowledgement & MTTN Calculation
 * 6. Multi-Tier Escalation Ladder (Cardiologist -> ICU Attending -> Crash Cart Code Team)
 * 7. Incident Resolution & Clinical Audit Logging
 * 8. Multi-Protocol Coverage (Ventricular Tachycardia, Severe Bradycardia, Critical Hypoxia, Hypertensive Crisis)
 */

const BASE_URL = process.env.API_BASE || "http://localhost:4000/api";

async function runTests() {
  console.log("================================================================================");
  console.log("🚨 RUNNING MILESTONE 3 TASK 3: REAL-TIME CLINICAL ALERT ENGINE TEST SUITE");
  console.log("================================================================================\n");

  let passed = 0;
  let failed = 0;

  function assert(condition, message) {
    if (condition) {
      console.log(`  ✓ PASS: ${message}`);
      passed++;
    } else {
      console.error(`  ✗ FAIL: ${message}`);
      failed++;
    }
  }

  // TEST 1: Engine Benchmark Statistics & On-Call Cardiologist Roster
  console.log("Test 1: Engine Benchmark Statistics & On-Call Cardiologist Roster");
  try {
    const res = await fetch(`${BASE_URL}/alerts/stats`).then((r) => r.json());
    assert(res.success === true, "Endpoint /api/alerts/stats responded with success: true");
    assert(res.stats?.status === "ACTIVE", `Alert engine status is ACTIVE (actual: ${res.stats?.status})`);
    assert(res.stats?.slaTargetMinutes <= 3.2, `SLA Target <= 3.2 minutes (actual: ${res.stats?.slaTargetMinutes} min)`);
    assert(res.stats?.slaPassed === true, `SLA Compliance target passed (rate: ${res.stats?.slaComplianceRate})`);
    assert(res.stats?.mttnPassed === true, `Mean Time to Notify (MTTN) target passed (actual: ${res.stats?.meanTimeToNotifyMinutes})`);
    assert(res.stats?.onCallCardiologist?.name === "Dr. Evelyn Reed, MD", `On-Call Cardiologist correctly assigned (${res.stats?.onCallCardiologist?.name})`);
    assert(res.stats?.onCallCardiologist?.status === "ON_DUTY", "On-Call Cardiologist status is ON_DUTY");
    assert(Array.isArray(res.stats?.channels) && res.stats.channels.length >= 4, `Multi-channel dispatch configured (${res.stats?.channels?.length} channels active)`);
  } catch (err) {
    assert(false, `Test 1 failed with error: ${err.message}`);
  }

  // TEST 2: Active Alerts and Cohort Query API
  console.log("\nTest 2: Active Alerts and Cohort Query API");
  try {
    const res = await fetch(`${BASE_URL}/alerts/active`).then((r) => r.json());
    assert(res.success === true, "Endpoint /api/alerts/active responded with success: true");
    assert(Array.isArray(res.alerts), `Active alerts array returned (count: ${res.count})`);

    const allRes = await fetch(`${BASE_URL}/alerts?limit=10`).then((r) => r.json());
    assert(allRes.success === true, "Endpoint /api/alerts query responded with success");
    assert(allRes.alerts.length >= 2, `Historical cohort seed alerts loaded (${allRes.alerts.length} found)`);
  } catch (err) {
    assert(false, `Test 2 failed with error: ${err.message}`);
  }

  // TEST 3: Signature Scenario - Sarah M. (P002) 145 bpm AFib Spike Simulation
  console.log("\nTest 3: Signature Scenario - Sarah M. (P002) 145 bpm AFib Alert Simulation");
  let testAlertId = null;
  try {
    const res = await fetch(`${BASE_URL}/alerts/simulate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ patientId: "P002", scenario: "afib_episode" })
    }).then((r) => r.json());

    assert(res.success === true, "Simulation endpoint /api/alerts/simulate succeeded");
    assert(res.alert !== null, "Alert object generated by Alert Engine");
    testAlertId = res.alert?.alertId;
    assert(res.alert?.patientId === "P002", `Alert assigned to patient P002 (actual: ${res.alert?.patientId})`);
    assert(res.alert?.patientName === "Sarah Miller", `Alert patient name is Sarah Miller (actual: ${res.alert?.patientName})`);
    assert(res.alert?.type === "POSSIBLE_AFIB", `Alert type is POSSIBLE_AFIB (actual: ${res.alert?.type})`);
    assert(res.alert?.severity === "CRITICAL", `Alert severity is CRITICAL (actual: ${res.alert?.severity})`);
    assert(res.alert?.status === "DISPATCHED", `Alert status is DISPATCHED (actual: ${res.alert?.status})`);
    assert(res.alert?.slaMinutes <= 3.2, `Alert SLA window <= 3.2 minutes (actual: ${res.alert?.slaMinutes} min)`);
    assert(res.alert?.physicianName === "Dr. Evelyn Reed, MD", `Assigned to Dr. Evelyn Reed, MD (actual: ${res.alert?.physicianName})`);
    assert(Boolean(res.alert?.deadlineTimestamp), `SLA deadline timestamp calculated (${res.alert?.deadlineTimestamp})`);
  } catch (err) {
    assert(false, `Test 3 failed with error: ${err.message}`);
  }

  // TEST 4: Clinical Decision Support (CDS) Order Sets Verification
  console.log("\nTest 4: Clinical Decision Support (CDS) Order Sets Generation");
  try {
    const res = await fetch(`${BASE_URL}/alerts?limit=5`).then((r) => r.json());
    const targetAlert = res.alerts.find((a) => a.alertId === testAlertId) || res.alerts[0];
    
    assert(Array.isArray(targetAlert?.orderSet) && targetAlert.orderSet.length >= 3, `CDS Order Set contains >= 3 orders (actual: ${targetAlert?.orderSet?.length})`);
    const statOrders = targetAlert?.orderSet?.filter((o) => o.urgent);
    assert(statOrders.length >= 1, `Contains STAT urgent orders (${statOrders.length} STAT orders found)`);
    const ecgOrder = targetAlert?.orderSet?.find((o) => o.name.toLowerCase().includes("ecg"));
    assert(Boolean(ecgOrder), `Order Set contains STAT 12-Lead ECG order (${ecgOrder?.name})`);
  } catch (err) {
    assert(false, `Test 4 failed with error: ${err.message}`);
  }

  // TEST 5: Clinician SLA Response Acknowledgement
  console.log("\nTest 5: Clinician SLA Response Acknowledgement & Claim");
  try {
    if (!testAlertId) throw new Error("Missing testAlertId from Test 3");

    const res = await fetch(`${BASE_URL}/alerts/${encodeURIComponent(testAlertId)}/acknowledge`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ clinician: "Dr. Evelyn Reed, MD" })
    }).then((r) => r.json());

    assert(res.success === true, `Alert ${testAlertId} acknowledged successfully`);
    assert(res.alert?.status === "ACKNOWLEDGED", `Status transitioned to ACKNOWLEDGED (actual: ${res.alert?.status})`);
    assert(res.alert?.acknowledgedBy === "Dr. Evelyn Reed, MD", `Acknowledged by recorded (${res.alert?.acknowledgedBy})`);
    assert(typeof res.alert?.mttnSeconds === "number", `Mean Time to Notify calculated (${res.alert?.mttnSeconds}s)`);
    assert(res.alert?.slaCompliant === true, "Response was SLA compliant (<= 3.2 minutes)");
  } catch (err) {
    assert(false, `Test 5 failed with error: ${err.message}`);
  }

  // TEST 6: Multi-Tier Escalation Ladder (Cardiologist -> Crash Cart Code Team)
  console.log("\nTest 6: Multi-Tier Escalation Ladder (Crash Cart Code Blue Escalation)");
  let escalationAlertId = null;
  try {
    // Generate a new alert for escalation test
    const simRes = await fetch(`${BASE_URL}/alerts/simulate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ patientId: "P004", scenario: "critical_tachycardia" })
    }).then((r) => r.json());

    escalationAlertId = simRes.alert?.alertId;
    assert(Boolean(escalationAlertId), "Spawned alert for emergency escalation test");

    const escRes = await fetch(`${BASE_URL}/alerts/${encodeURIComponent(escalationAlertId)}/escalate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ reason: "Unacknowledged within SLA / Acute Ventricular Arrhythmia" })
    }).then((r) => r.json());

    assert(escRes.success === true, "Escalation API responded with success: true");
    assert(escRes.alert?.status === "ESCALATED", `Status transitioned to ESCALATED (actual: ${escRes.alert?.status})`);
    assert(escRes.alert?.severity === "EMERGENCY", `Severity upgraded to EMERGENCY (actual: ${escRes.alert?.severity})`);
    assert(escRes.alert?.targetRole === "CRASH_CART_CODE_TEAM", `Target role escalated to CRASH_CART_CODE_TEAM (actual: ${escRes.alert?.targetRole})`);
    assert(Boolean(escRes.alert?.escalatedAt), `Escalation timestamp logged (${escRes.alert?.escalatedAt})`);
  } catch (err) {
    assert(false, `Test 6 failed with error: ${err.message}`);
  }

  // TEST 7: Clinical Incident Resolution & Audit Trail Documentation
  console.log("\nTest 7: Clinical Incident Resolution & Audit Trail Documentation");
  try {
    const targetId = testAlertId || escalationAlertId;
    const res = await fetch(`${BASE_URL}/alerts/${encodeURIComponent(targetId)}/resolve`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        resolutionNotes: "Administered IV Diltiazem 0.25mg/kg. Patient returned to normal sinus rhythm at 76 bpm. 12-Lead ECG confirmed stability.",
        clinician: "Dr. Evelyn Reed, MD"
      })
    }).then((r) => r.json());

    assert(res.success === true, `Alert ${targetId} resolved successfully`);
    assert(res.alert?.status === "RESOLVED", `Status transitioned to RESOLVED (actual: ${res.alert?.status})`);
    assert(res.alert?.resolvedBy === "Dr. Evelyn Reed, MD", `Resolved by recorded (${res.alert?.resolvedBy})`);
    assert(res.alert?.resolutionNotes.includes("IV Diltiazem"), "Resolution clinical notes saved accurately");
    assert(res.alert?.orderSet.every((o) => o.status === "COMPLETED"), "All CDS order set items marked as COMPLETED");
  } catch (err) {
    assert(false, `Test 7 failed with error: ${err.message}`);
  }

  // TEST 8: Multi-Protocol CDS Coverage (Bradycardia, Hypoxia, Hypertensive Crisis)
  console.log("\nTest 8: Multi-Protocol CDS Coverage (Hypoxia & Hypertensive Crisis)");
  try {
    const hypoxiaRes = await fetch(`${BASE_URL}/alerts/simulate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ patientId: "P005", scenario: "hypoxia" })
    }).then((r) => r.json());

    assert(hypoxiaRes.success === true, "Critical hypoxia alert simulated");
    assert(hypoxiaRes.alert?.type === "CRITICAL_HYPOXIA" || hypoxiaRes.alert?.condition.includes("Hypoxia"), `Hypoxia condition identified (${hypoxiaRes.alert?.condition})`);

    const hyperRes = await fetch(`${BASE_URL}/alerts/simulate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ patientId: "P003", scenario: "hypertensive_spike" })
    }).then((r) => r.json());

    assert(hyperRes.success === true, "Hypertensive crisis alert simulated");
    assert(hyperRes.alert?.type === "HYPERTENSIVE_CRISIS" || hyperRes.alert?.condition.includes("Hypertensive"), `Hypertensive crisis condition identified (${hyperRes.alert?.condition})`);
  } catch (err) {
    assert(false, `Test 8 failed with error: ${err.message}`);
  }

  console.log("\n================================================================================");
  console.log(`TOTAL PASSED: ${passed} | TOTAL FAILED: ${failed}`);
  console.log("================================================================================");

  if (failed > 0) {
    process.exit(1);
  }
}

runTests();
